# routes/odm_routes.py
RUTAS_ODM = [
    "CREAR_ODM",
    "ACTUALIZAR_ESTADO_ODM",
    "OBTENER_ODM",
    "LISTAR_ODMS",
    "FILTRAR_ODMS",
    "REASIGNAR_TECNICO_ODM",
    "AGREGAR_NOTA_ODM",
    "RESUMEN_COSTOS",
    "REPORTE_DESEMPENO",
    "REPORTE_EQUIPOS_CRITICOS",
    "EXPORTAR_CSV",
]
